name: Flutter Build App

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: flutter build app
    runs-on: macos-latest
    
    env:
      JAVA_VERSION: "17.0.1"
      FLUTTER_VERSION: "2.5.3"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: ${{env.JAVA_VERSION}}
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: ${{env.FLUTTER_VERSION}}
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk --info
    - run: flutter build ios --release --no-codesign
